### ISSUE TITLE
Python 3 issue with hashlib.sha1() for unique ID?

### ISSUE THREAD

**Issue by hkkenneth** [knockrentals/scrapy-elasticsearch#41]
I am recently changing from python 2 to 3, not sure if this is a valid issue.

When I configured my `ELASTICSEARCH_UNIQ_KEY` value, I ran into a problem - if my unique ID is str, `hashlib.sha1()` complains:

```
TypeError: Unicode-objects must be encoded before hashing
```

If I `.encode('utf-8')` the ID before putting it in the field, line 73 in `scrapyelasticsearch.py` complains `'unique key must be str'`

To work around it, I have to put the ID in a list!

What's the purpose of `if isinstance(unique_key, list):` in the `def get_unique_key(self, unique_key)` method?

**Comment by jayzeng** [comment]
@hkkenneth are you passing in unicode (language other than English) as unique id?

**Comment by hkkenneth** [comment]
@jayzeng I only have ascii alphanumeric characters. But isn't it all strings are using Unicode in Python 3?

**Comment by jayzeng** [comment]
@hkkenneth I just committed a fix (https://github.com/knockrentals/scrapy-elasticsearch/commit/320cec117d213c7530a4d17b126deccbd5409eb7), give it a try and let me know how it goes. 

Back to your question, you can pass in either a string/unicode, or a list for unique key (which it will use the 1st element from the list).

**Comment by hkkenneth** [comment]
It doesn't work... Can we clarify a bit? If I am not passing in a list - just a single key, should I pass in the value before or after `.encode('utf-8')`? If I encode it first, its class is `<class 'bytes'>` and I still got the exception. If I don't encode it, `hashlib.sha1()` complains.

I am using python 3.5.2.

**Comment by jayzeng** [comment]
@hkkenneth sorry for the delay, I just tested again w/ Python 3 (don't have 3.5.2) and it works fine. You should just pass in the value (without invoking .encode('utf-8') because the code does it for you). One thing I don't get is why the class is 'bytes' rathe than 'str' or 'unicode'? 

If you look at this line:
https://github.com/knockrentals/scrapy-elasticsearch/blob/master/scrapyelasticsearch/scrapyelasticsearch.py#L74, I would recommend you to pass in a string rather than a list as your unique key (which is what you set in ELASTICSEARCH_UNIQ_KEY)

Feel free to email me personally if you are still stuck

**Comment by PPACI** [comment]
I had a solution in my local copy of scrapy-elastic. I created a pull request for this : #50

**Comment by jayzeng** [comment]
That's an oversight on my side, thanks @PPACI! I cut a new build w/ the fix, @hkkenneth please give it a shot.
