### ISSUE TITLE
How to handle deleted documents?

### ISSUE THREAD

**Issue by burnash** [knockrentals/scrapy-elasticsearch#46]
Example: I'm crawling an API with JSON documents. From time to time some documents get removed from the source database and are missing in the API. How to handle this with scrapy-elasticsearch to keep es up to date?

From [the source code](https://github.com/knockrentals/scrapy-elasticsearch/blob/320cec117d213c7530a4d17b126deccbd5409eb7/scrapyelasticsearch/scrapyelasticsearch.py#L86), I can see that there's no `_op_type` parameter specified in the `bulk` call so it probably resorts to default 'index'.

**Comment by jayzeng** [comment]
@burnash sorry, I don't fully understand your question, are you saying the documents don't get written to es occasionally? or you are looking for a way to make sure your es data mirrors your source data, in another word, when there is data being removed from source, you want it to be also removed from es?

**Comment by burnash** [comment]
@jayzeng Yes, Exactly this:
> you are looking for a way to make sure your es data mirrors your source data, in another word, when there is data being removed from source, you want it to be also removed from es?

But I'm not in control of the source data server so I can't send / receive any signals when data gets removed.

**Comment by jayzeng** [comment]
Well, I see two ways to achieve what you want:
1) delete the entire index and re-sync, this should work fine if your data size is small and relatively slow(er). It is easy to implement and guarantees old data will be remove.
2) fetch (w/ ES mget) all documents, you can compute the hash of your data and pass these ids, then compute the differences (by differing the sets) and remove the removed data. It gets tricky since library does a bulk operation and you may need to pull all the documents' ids upfront (which shouldn't be too bad if you are only fetching the ids) and store them in memory for differing for each batch. 

However, I don't see this library should attempt to do these magic for you. You can extend the library and build on top. I am happy to assist if you need help.

**Comment by burnash** [comment]
@jayzeng Thanks for the suggestions, I used to use (1) in my indexing script but it turned out too slow. So I switched to a variation of (2) but with `scan and scroll` instead of `mget`. I was thinking of using scrapy instead of my own crawler. If I move to scrapy I'll try to extend the library.
